name: Kind Antrea Cyclonus
on:
#  push:
#  pull_request:
  workflow_dispatch:
  schedule:
    # See https://crontab.guru/#0_0_*_*_0:
    #   At 00:00 on Sunday.
    - cron: '0 0 * * 0'

env:
  KIND_VERSION: v0.9.0

jobs:

  test-kind-antrea:
    name: Run Cyclonus on KinD/Antrea
    runs-on: [ubuntu-18.04]
    steps:
      - name: Free disk space
        # https://github.com/actions/virtual-environments/issues/709
        run: |
          sudo apt-get clean
          df -h
      - uses: actions/checkout@v2
#      - run: make
      - name: Install Kind
        run: |
          curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-$(uname)-amd64
          chmod +x ./kind
          sudo mv kind /usr/local/bin
      - name: Run cyclonus tests
        working-directory: hack/antrea
        run: ./github-action.sh
